// MACC_N_CHEESE Grammar 2016
// 
// Parser Class Definition File

// SHELL GENERATED BY PARSERGEN VERSION 5.0.3

#ifndef PARSER
#define PARSER

#include <string>
using namespace std;

#include "mncScan.h" // scanner class definition

#include "mncCode.h" // code generator class definition

class Parser
{
public:

	Parser();

	void SystemGoal();

private:

	Token savedToken;
	bool  tokenAvailable;

	void SyntaxError(Token t, string msg);

	Token NextToken();

	void Match(Token t);

	void InitTail();

	void VarDecTail();

	void VarDecList(ExprType& type, bool HipOrNah, int HipHip_Size);

	void DecTail();

	void Declaration();

	void DecList();

	void BoolLit(Expr& expr);

	void CheeseTypeTail(int& Cheese_size);

	void CheeseType(int& Cheese_size);

	void Type(ExprType& type, int& Cheese_size);

	void Literal(Expr& expr);

	void MultOp();

	void FactorTail();

	void Primary(Expr& expr);

	void AddOp();

	void ExprTail();

	void Factor(Expr& expr);

	void RelOp();

	void CondTail();

	void IntListTail();

	void IntList();

	void CaseListTail();

	void Case();

	void CaseList();

	void ForAssign();

	void ElseClause();

	void Condition();

	void VarDecs();

	void SelectStmt();

	void ForStmt();

	void WhileStmt();

	void LoopStmt();

	void IfStmt();

	void ItemListTail();

	void ItemList();

	void VariableTail();

	void VarListTail();

	void VarList();

	void InitList();

	void Expression(Expr& expr);

	void AssignTail();

	void Variable();

	void BreakStmt();

	void ShoutStmt();

	void ListenStmt();

	void AssignStmt();

	void StructStmt();

	void SimpleStmt();

	void StmtTail();

	void Statement();

	void StmtList();

	void Program();

	void SyntaxError();

}; // end of Parser class

#endif
